### ISSUE TITLE
Live Eval displays mate Eval as 0

### ISSUE THREAD

**Issue by vasya-1965** [coolchess123/tcec-gui#128]
Since DivP live eval (SF128 and CFish) displays the eval of a PV ending in mate as 0. It's like it is configured to display eval only in numbers and not something like M23.

For example in the fourth SF-IH games it read as "CFish 7 men TB [88] PV 0" . The PV of CFish ended in a mate. SF also displayed a mate score.

 It is similar to the bug (now fixed) which resulted in mate scores of playing engines being displayed as NaN.

**Comment by vasya-1965** [comment]
![example](https://user-images.githubusercontent.com/43521936/46550211-fd786700-c8f1-11e8-820f-23e0acb13be0.png)

CFish PV is a mate. Also SF eval. But CFish eval is displayed as 0

**Comment by xoto10** [comment]
If adjusting the "Live Engine" how about changing it's name, "Live Engine" seems a bit odd? 

Could just say "Analysis" in the eval graph and then the PV area could have something like "Analysis (... details ...) PV X.YZ". That way the name is short but obvious in the eval graph and there is a clear link to the PV with the word "Analysis".

**Comment by coolchess123** [comment]
fixed
