### ISSUE TITLE
Buttons under main board 

### ISSUE THREAD

**Issue by Khagrin2** [coolchess123/tcec-gui#167]
![image](https://user-images.githubusercontent.com/40367843/48077115-a5fd3d80-e1b4-11e8-85f0-879473634d9a.png)

Note the "border" issue ... i.e. no border between some buttons.  I have found this problem to not really be solvable across browsers/zooms/resolutions.   Easy solution is:  (1) remove the right borders in the button group;  (2) remove the borders of buttons themselves.  This makes a seemless bar.  I would also suggest setting the button background to be simply transparent rather than blue ... note the "hover" highlights will still be fine.  If you do this you should choose nice colors for the button images that will work on light and dark themes and still complement the blue "hover" highlights.  White or wheat is okay for dark theme, don't know what would work best for light theme.

**Comment by coolchess123** [comment]
fixed
