### ISSUE TITLE
Add a permanent moves-to-50mr

### ISSUE THREAD

**Issue by WarpRules** [coolchess123/tcec-gui#179]
I think there's plenty of space in the new gui to add a permanent small "moves to 50-move rule" somewhere. This kind of information can be interesting to see, and currently it's not always displayed.

**Comment by awbgithub** [comment]
this could also be a solution to the problem mentioned in https://github.com/scs-ben/tcec-gui/issues/140 ... i.e. if there were a permanent "50 mr" indicator then there would be no need to flip between the "plies to draw" counter and the "50 mr" counter.

**Comment by coolchess123** [comment]
done
