### ISSUE TITLE
number of crashes in standings table seems to zero out after each game

### ISSUE THREAD

**Issue by awbgithub** [coolchess123/tcec-gui#184]
cbvb has a crash in div2 of season 14 ... but after each game the number of crashes shows 0 (zero) for all engines unless I refresh the UI. Then crashes shows correctly until the next game starts - at which point the crashes shows 0 for all engines again until I refresh the UI again.

**Comment by Badenlebt** [comment]
The losses also get zeroed...

**Comment by coolchess123** [comment]
fixed in cutechess
