### ISSUE TITLE
Sorting the crosstable consistently

### ISSUE THREAD

**Issue by UsuallyLogical** [coolchess123/tcec-gui#193]
Normally, the rows and columns of a crosstable are sorted the same way (resulting in a nice diagonal of black boxes where a player intersects with itself). But the tcec doesn't always do this, which makes the crosstable a bit harder to read.
![image](https://user-images.githubusercontent.com/44342694/51264100-8465c280-196a-11e9-965c-b4ae311b198f.png)
Can this be fixed?

**Comment by coolchess123** [comment]
shud be fixed
