### ISSUE TITLE
Access to kibitzer data

### ISSUE THREAD

**Issue by dcorbit** [coolchess123/tcec-gui#195]
I would very much like to get the data produced by the Kibitzing engines because that data is often of higher quality than the data produced by the contest engines.

If you could create an additional download for the Kibitzing engines data, I (and others I am sure) would be extremely grateful.

-- Dann Corbit

**Comment by coolchess123** [comment]
done

**Comment by dcorbit** [comment]
I am absurdly grateful for this.  I guess that other people will like it too. Thank you very much.
