### ISSUE TITLE
TCEC GUI badly highlight king-castling squares

### ISSUE THREAD

**Issue by checkqmate** [coolchess123/tcec-gui#197]
Hi all! 
I found a small TCEC GUI bug/improvement:
When players choose to king-castling (O-O), the GUI badly displays the move.
For example, considering White side king-castling, GUI highlight e1 and h1, where it should be e1 and g1 instead, because castling is considered as a king's move, not a rook's move.
Src: https://en.wikipedia.org/wiki/Castling#Tournament_rules

**Comment by coolchess123** [comment]
chessboard js does it that way, cant help
