### ISSUE TITLE
Android Firefox ChessBoard error 1002

### ISSUE THREAD

**Issue by rackbrain** [coolchess123/tcec-gui#198]
On Android OS 6.0.1 phone using Firefox 64, this error appears immediately upon accessing tcec.chessdom.com:
"ChessBoard Error 1002:
Element with id "pv-boarda" does not exist in the DOM.
Exiting ..."

This does not occur on the same phone using Chrome.

**Comment by coolchess123** [comment]
I think it was a bad merge issue 

Was fixed
