### ISSUE TITLE
Live eval/PV of thinking engine

### ISSUE THREAD

**Issue by robx** [coolchess123/tcec-gui#200]
Apologies if this is out of scope for the gui since it probably requires backend changes. But:

It'd be great to be able to follow along the search process as an engine is thinking about the move to play, particularly with long time controls such as in the superfinal. E.g. you'd see your favorite engine looking at a bad move at low depth and pray for it to change its mind.

Concretely, this should involve getting the `info` engine output and relaying it to the frontend. There, a possible way to show this would be to treat it similarly to the current kibitzing engines, and/or maybe to update the main eval/PV display but style it differently to indicate that it's not a final result.

**Comment by coolchess123** [comment]
fixed
