### ISSUE TITLE
Add Book FAQ to GUI Menu Bar

### ISSUE THREAD

**Issue by tcecspectator** [coolchess123/tcec-gui#210]
Please add 'Book FAQ' to the GUI menu bar that behaves identical to the Rules Menu option.  When the 'Book FAQ' menu option is clicked, a pop-out window will display the Book FAQ.  Place this 'Book FAQ' between the current menu options 'Rules' and 'Archive'

**Comment by coolchess123** [comment]
I am making it open another link which is easier to read the file
