### ISSUE TITLE
[URGENT] Twitch stream broken for 2 days

### ISSUE THREAD

**Issue by kanchess** [coolchess123/tcec-gui#226]
TCEC has been broadcasting constantly on Twitch, but this suddenly broke 2 days ago, what was changed to the regular url for streaming does no longer work?
This url has been forwarded to you earlier today by confidential pm.

Please fix the stream asap, as this is one of TCEC primary broadcasting channels, not only the most important path for new viewers to find TCEC, but we also need the statistics.

Thank you in advance!

**Comment by coolchess123** [comment]
Oh secret url, i did not know, i guess the person who created the url does not know it exists, interesting

**Comment by kanchess** [comment]
the person who created the url is ben, and it has been in use ever since by rodrigo who actually pays for having this stream up as donation to tcec fyi

**Comment by coolchess123** [comment]
ok since i have never fixed it earlier, plz ask ben
