### ISSUE TITLE
Slow down moves with minimal delay.

### ISSUE THREAD

**Issue by Dorus** [coolchess123/tcec-gui#234]
I would suggest something like a 1 second minimal delay between moves (on the GUI). Right now sometimes you can completely miss moves when the engines instant move during forced sequences or when in time trouble. On phone this does not make it easy to follow.

Moves could still be added to the move list, but the board would behave as if you clicked back a move and selected the play button.

**Comment by coolchess123** [comment]
not feasible sorry
