### ISSUE TITLE
Black engine pv links to live pv board (PV(A))

### ISSUE THREAD

**Issue by Dorus** [coolchess123/tcec-gui#236]
Clicking on the PV for the black engine links to the PV(A) board insterad of the PV board. For the white engine it does link to PV board correctly, but seems to only do so once you've used the PV board manually.

**Comment by coolchess123** [comment]
It happens only during the analysis eval, if you click on stable pv it opens up properly, its by design

**Comment by Dorus** [comment]
I fail to see how this is good design, as the live PV(A) pv board is for bluefish, not the engine playing.
