### ISSUE TITLE
Width of "Adj Rule" in event overview keeps changing

### ISSUE THREAD

**Issue by bugdebugger** [coolchess123/tcec-gui#65]
This is just a little annoyance.

As the text in the "Adj Rule" column keeps changing from e.g. `-` to `X moves to 50mr` to `X plies to draw` the width of all the columns in the event overview changes. This means lots of moving text and thus visual noise. This is especially noticeable on fast TC .

I would suggest to check what is the longest (widest) Adj Rule text and then set a sensible fixed width for the Adj Rule column to fix the recurring resizing of the event overview.

**Comment by arunsathya1309** [comment]
tried a fix, let me know if it works for u
